version: "3.7"
services:
    mariadb:
        image: docker.io/bitnami/mariadb:10.3
        environment:
            - MARIADB_ROOT_PASSWORD=barangmudo007
        ports:
            - 3306:3306
        networks:
            - databases
        volumes:
            - ./database/db_bm.sql:/docker-entrypoint-initdb.d/dump.sql
        container_name: mariadb
    phpmyadmin:
        image: ranur/phpmyadmin:1.1-links
        ports:
            - 85:80
        container_name: phpmyadmin
networks:
    databases:
        external: true
        
        