version: "3.7"
services:
  web:
    image: ranur/codeigniter:3.11-sessions
    volumes:
      - ./dashboard-api/:/app/myapp
    ports:
      - 90:8000
    networks:
      - databases
    container_name: container-api
networks:
  databases:
    external: true
